const posts = [
  {
    id: "clx1a01e10001",
    createdAt: new Date(),
    slug: "mastering-react-hooks",
    title: "Mastering React Hooks",
    desc: "### Quick Intro\nLearn how to use React Hooks effectively.",
    img: "https://images.unsplash.com/photo-1581276879432-15a19d654956",
    views: 0,
    categoryId: "cat1",
    userEmail: "john@example.com",
  },
  {
    id: "clx1a01e10002",
    createdAt: new Date(),
    slug: "nodejs-performance-tips",
    title: "Node.js Performance Tips",
    desc: "### Guide\nOptimize your Node.js apps with these quick tips.",
    img: "https://images.unsplash.com/photo-1556761175-129418cb2dfe",
    views: 0,
    categoryId: "cat2",
    userEmail: "jane@example.com",
  },
  {
    id: "clx1a01e10003",
    createdAt: new Date(),
    slug: "understanding-nextjs-routing",
    title: "Understanding Next.js Routing",
    desc: "### Routing Basics\nHow Next.js handles file-based routing.",
    img: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
    views: 0,
    categoryId: "cat1",
    userEmail: "john@example.com",
  },
  {
    id: "clx1a01e10004",
    createdAt: new Date(),
    slug: "introduction-to-prisma",
    title: "Introduction to Prisma",
    desc: "### ORM Basics\nLearn how Prisma simplifies database access.",
    img: "https://images.unsplash.com/photo-1549921296-3a7d7d2f2a33",
    views: 0,
    categoryId: "cat3",
    userEmail: "alice@example.com",
  },
  {
    id: "clx1a01e10005",
    createdAt: new Date(),
    slug: "tailwind-css-best-practices",
    title: "Tailwind CSS Best Practices",
    desc: "### Quick Tips\nHow to structure your Tailwind projects.",
    img: "https://images.unsplash.com/photo-1587613991192-9521e5caa6d7",
    views: 0,
    categoryId: "cat4",
    userEmail: "mark@example.com",
  },
  {
    id: "clx1a01e10006",
    createdAt: new Date(),
    slug: "javascript-es2023-features",
    title: "JavaScript ES2023 Features",
    desc: "### What's New\nA look at the latest JavaScript features.",
    img: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    views: 0,
    categoryId: "cat2",
    userEmail: "jane@example.com",
  },
  {
    id: "clx1a01e10007",
    createdAt: new Date(),
    slug: "building-rest-apis-express",
    title: "Building REST APIs with Express",
    desc: "### Step by Step\nCreate scalable REST APIs using Express.",
    img: "https://images.unsplash.com/photo-1504805572947-34fad45aed93",
    views: 0,
    categoryId: "cat2",
    userEmail: "john@example.com",
  },
  {
    id: "clx1a01e10008",
    createdAt: new Date(),
    slug: "authentication-with-jwt",
    title: "Authentication with JWT",
    desc: "### Security\nLearn JWT-based authentication in Node.js.",
    img: "https://images.unsplash.com/photo-1557804506-669a67965ba0",
    views: 0,
    categoryId: "cat2",
    userEmail: "alice@example.com",
  },
  {
    id: "clx1a01e10009",
    createdAt: new Date(),
    slug: "deploying-nextjs-vercel",
    title: "Deploying Next.js on Vercel",
    desc: "### Hosting Guide\nDeploy your Next.js apps seamlessly.",
    img: "https://images.unsplash.com/photo-1522199710521-72d69614c702",
    views: 0,
    categoryId: "cat1",
    userEmail: "mark@example.com",
  },
  {
    id: "clx1a01e10010",
    createdAt: new Date(),
    slug: "graphql-vs-rest",
    title: "GraphQL vs REST",
    desc: "### Comparison\nExplore the differences between GraphQL and REST.",
    img: "https://images.unsplash.com/photo-1505678261036-a3fcc5e884ee",
    views: 0,
    categoryId: "cat3",
    userEmail: "john@example.com",
  },
  {
    id: "clx1a01e10011",
    createdAt: new Date(),
    slug: "database-relationships-prisma",
    title: "Database Relationships in Prisma",
    desc: "### Relational Mapping\nUnderstand how to model relations in Prisma.",
    img: "https://images.unsplash.com/photo-1581091215367-59ab6c6c25b1",
    views: 0,
    categoryId: "cat3",
    userEmail: "alice@example.com",
  },
  {
    id: "clx1a01e10012",
    createdAt: new Date(),
    slug: "serverless-functions-overview",
    title: "Serverless Functions Overview",
    desc: "### Cloud Functions\nIntroduction to serverless computing.",
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475",
    views: 0,
    categoryId: "cat4",
    userEmail: "mark@example.com",
  },
  {
    id: "clx1a01e10013",
    createdAt: new Date(),
    slug: "zustand-state-management",
    title: "State Management with Zustand",
    desc: "### Lightweight Store\nLearn about Zustand for React state.",
    img: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    views: 0,
    categoryId: "cat1",
    userEmail: "jane@example.com",
  },
  {
    id: "clx1a01e10014",
    createdAt: new Date(),
    slug: "docker-basics-for-devs",
    title: "Docker Basics for Developers",
    desc: "### Containers\nA beginner’s guide to Docker for devs.",
    img: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb",
    views: 0,
    categoryId: "cat4",
    userEmail: "john@example.com",
  },
  {
    id: "clx1a01e10015",
    createdAt: new Date(),
    slug: "typescript-best-practices",
    title: "TypeScript Best Practices",
    desc: "### Tips\nImprove your TypeScript projects with these practices.",
    img: "https://images.unsplash.com/photo-1549924231-f129b911e442",
    views: 0,
    categoryId: "cat2",
    userEmail: "alice@example.com",
  },
  {
    id: "clx1a01e10016",
    createdAt: new Date(),
    slug: "react-query-intro",
    title: "Getting Started with React Query",
    desc: "### Fetching Data\nSimplify data fetching with React Query.",
    img: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    views: 0,
    categoryId: "cat1",
    userEmail: "mark@example.com",
  },
  {
    id: "clx1a01e10017",
    createdAt: new Date(),
    slug: "improving-seo-nextjs",
    title: "Improving SEO in Next.js",
    desc: "### SEO Tips\nEnhance your SEO with Next.js built-in tools.",
    img: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    views: 0,
    categoryId: "cat1",
    userEmail: "john@example.com",
  },
  {
    id: "clx1a01e10018",
    createdAt: new Date(),
    slug: "error-handling-nodejs",
    title: "Error Handling in Node.js",
    desc: "### Handling Errors\nLearn patterns for handling errors in Node apps.",
    img: "https://images.unsplash.com/photo-1504805572947-34fad45aed93",
    views: 0,
    categoryId: "cat2",
    userEmail: "jane@example.com",
  },
  {
    id: "clx1a01e10019",
    createdAt: new Date(),
    slug: "ci-cd-pipelines",
    title: "CI/CD Pipelines Explained",
    desc: "### Automation\nLearn how to automate deployment with CI/CD.",
    img: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7",
    views: 0,
    categoryId: "cat4",
    userEmail: "mark@example.com",
  },
  {
    id: "clx1a01e10020",
    createdAt: new Date(),
    slug: "monorepos-with-nx",
    title: "Monorepos with Nx",
    desc: "### Structure\nLearn how Nx helps you manage monorepos.",
    img: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    views: 0,
    categoryId: "cat4",
    userEmail: "alice@example.com",
  },
];
