services:
  blog-app:
    # container_name: blog-app
    build:
      context: .
      target: development
    # env_file:
    #   - ./.env
    image: blog-app:dev
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - /app/node_modules # prevents node_modules overwrite.
    command: npm run local:watch
    environment:
      - debug=true
    networks:
      - blog-app-network

  mysql:
    image: mysql
    container_name: my-mysql-blog-app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blog-app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: my-phpmyadmin-blog-app
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: mypassword
    networks:
      - blog-app-network

  redis:
    image: redis
    container_name: my-redis-blog-app
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_blog_app_data:/data
    networks:
      - blog-app-network

volumes:
  blog-app-volume:
  mysql_data:
  redis_blog_app_data:
