const comments = [
  {
    id: "c1",
    content: "Great explanation!",
    postId: "clx1a01e10001",
    userId: "u2",
    createdAt: new Date(),
  },
  {
    id: "c2",
    content: "This helped me a lot, thanks!",
    postId: "clx1a01e10001",
    userId: "u3",
    createdAt: new Date(),
  },
  {
    id: "c3",
    content: "Adding this to my travel bucket list.",
    postId: "clx1a01e10002",
    userId: "u1",
    createdAt: new Date(),
  },
  {
    id: "c4",
    content: "Super useful budgeting guide.",
    postId: "clx1a01e10003",
    userId: "u4",
    createdAt: new Date(),
  },
  {
    id: "c5",
    content: "AI will truly change classrooms!",
    postId: "clx1a01e10004",
    userId: "u5",
    createdAt: new Date(),
  },
  {
    id: "c6",
    content: "I’m trying this morning routine tomorrow.",
    postId: "clx1a01e10005",
    userId: "u6",
    createdAt: new Date(),
  },
  {
    id: "c7",
    content: "TypeScript has been a game changer for me.",
    postId: "clx1a01e10006",
    userId: "u1",
    createdAt: new Date(),
  },
  {
    id: "c8",
    content: "I traveled solo last year, unforgettable!",
    postId: "clx1a01e10007",
    userId: "u2",
    createdAt: new Date(),
  },
  {
    id: "c9",
    content: "Stocks are scary but rewarding.",
    postId: "clx1a01e10008",
    userId: "u3",
    createdAt: new Date(),
  },
  {
    id: "c10",
    content: "Coursera has been my go-to.",
    postId: "clx1a01e10009",
    userId: "u4",
    createdAt: new Date(),
  },
  {
    id: "c11",
    content: "Minimalism simplified my life!",
    postId: "clx1a01e10010",
    userId: "u5",
    createdAt: new Date(),
  },
  {
    id: "c12",
    content: "Quantum computing is the future.",
    postId: "clx1a01e10011",
    userId: "u6",
    createdAt: new Date(),
  },
  {
    id: "c13",
    content: "Budget hacks worked for me in Asia.",
    postId: "clx1a01e10012",
    userId: "u1",
    createdAt: new Date(),
  },
  {
    id: "c14",
    content: "Retirement planning is underrated.",
    postId: "clx1a01e10013",
    userId: "u2",
    createdAt: new Date(),
  },
  {
    id: "c15",
    content: "Excited for these startups!",
    postId: "clx1a01e10014",
    userId: "u3",
    createdAt: new Date(),
  },
  {
    id: "c16",
    content: "I do these workouts every morning.",
    postId: "clx1a01e10015",
    userId: "u4",
    createdAt: new Date(),
  },
  {
    id: "c17",
    content: "Node.js tips are golden.",
    postId: "clx1a01e10016",
    userId: "u5",
    createdAt: new Date(),
  },
  {
    id: "c18",
    content: "Cultural respect makes travel better.",
    postId: "clx1a01e10017",
    userId: "u6",
    createdAt: new Date(),
  },
  {
    id: "c19",
    content: "Crypto feels risky compared to stocks.",
    postId: "clx1a01e10018",
    userId: "u1",
    createdAt: new Date(),
  },
  {
    id: "c20",
    content: "Gamification kept me motivated.",
    postId: "clx1a01e10019",
    userId: "u2",
    createdAt: new Date(),
  },
  {
    id: "c21",
    content: "Balance is the key to success.",
    postId: "clx1a01e10020",
    userId: "u3",
    createdAt: new Date(),
  },
  {
    id: "c22",
    content: "Could you share more examples?",
    postId: "clx1a01e10001",
    userId: "u4",
    createdAt: new Date(),
  },
  {
    id: "c23",
    content: "Loved your personal take.",
    postId: "clx1a01e10002",
    userId: "u5",
    createdAt: new Date(),
  },
  {
    id: "c24",
    content: "Waiting for part 2 of this!",
    postId: "clx1a01e10003",
    userId: "u6",
    createdAt: new Date(),
  },
  {
    id: "c25",
    content: "The AI discussion is spot on.",
    postId: "clx1a01e10004",
    userId: "u1",
    createdAt: new Date(),
  },
  {
    id: "c26",
    content: "This routine really works.",
    postId: "clx1a01e10005",
    userId: "u2",
    createdAt: new Date(),
  },
  {
    id: "c27",
    content: "Stocks vs crypto is always debated!",
    postId: "clx1a01e10018",
    userId: "u3",
    createdAt: new Date(),
  },
  {
    id: "c28",
    content: "Can you recommend learning apps?",
    postId: "clx1a01e10009",
    userId: "u4",
    createdAt: new Date(),
  },
  {
    id: "c29",
    content: "Work-life balance is underrated.",
    postId: "clx1a01e10020",
    userId: "u5",
    createdAt: new Date(),
  },
  {
    id: "c30",
    content: "Travel hacks are gold!",
    postId: "clx1a01e10012",
    userId: "u6",
    createdAt: new Date(),
  },
];
